- name: Verify connection to target host
  ansible.builtin.debug:
    msg: "Successfully connected to {{ ansible_host }}"

- name: Get system information
  debug: msg="{{ item }}"
  with_items: 
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_all_ipv4_addresses }}"
  - "{{ ansible_facts.os_family }}"
  - "{{ ansible_user }}"